language: rust
rust:
  - 1.19.0
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo build --verbose --manifest-path kodama-capi/Cargo.toml
  - cargo build --verbose --manifest-path kodama-bin/Cargo.toml
  - cargo test --verbose
  - cargo doc
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo bench --verbose --no-run;
    fi
